### PR TITLE
update to use `=~` to support older versions of ruby (<2.4)

### PR DESCRIPTION
**Pull request by cianmce**
Running an older version of Ruby produces the following error
```
bundler: failed to load command: rubocop-daemon (/Users/username/.rbenv/versions/2.2.8/bin/rubocop-daemon)
NoMethodError: undefined method `match?' for "1":String
  /Users/username/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/rubocop-daemon-0.3.1/lib/rubocop/daemon/client_command/exec.rb:31:in `exit_with_status!'
  /Users/username/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/rubocop-daemon-0.3.1/lib/rubocop/daemon/client_command/exec.rb:16:in `run'
  /Users/username/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/rubocop-daemon-0.3.1/lib/rubocop/daemon/cli.rb:38:in `create_subcommand_instance'
  /Users/username/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/rubocop-daemon-0.3.1/lib/rubocop/daemon/cli.rb:19:in `run'
  /Users/username/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/rubocop-daemon-0.3.1/exe/rubocop-daemon:8:in `<top (required)>'
  /Users/username/.rbenv/versions/2.2.8/bin/rubocop-daemon:23:in `load'
  /Users/username/.rbenv/versions/2.2.8/bin/rubocop-daemon:23:in `<top (required)>'
```

`.match?` was added in Ruby2.4 (https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/)

This is the only place where an exclusive Ruby 2.4+ method is used

With this change, the gem works as expected on older versions. Confirmed on 2.2, 2.3 and it continues to work on 2.4+

### CODE REVIEW

**Review by fohte — APPROVED** [review]
Thanks for your contribution! LGTM.

Ruby 2.3 or under have already reached end-of-life, but rubocop-daemon does not have support policy, so maybe we should support them.

**Comment by fohte** [comment]
I've released v0.3.2 with these changes! :tada:

* https://github.com/fohte/rubocop-daemon/releases/tag/v0.3.2
* https://rubygems.org/gems/rubocop-daemon/versions/0.3.2
